version: "3.0"

services:
  
  redis:
    image: "redis"
    ports: 
      - "6379:6379"

  db:
    image: "postgres" # use latest official postgres version
    environment:
        POSTGRES_USER: chat_user
        POSTGRES_PASSWORD: chat_password
        POSTGRES_DB: chat_database
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./:/app/
    tty: true
    depends_on:
      - "redis"
      - "db"
    environment:
      SECRET_KEY: 'some_really_secret'
      REDIS_HOST: redis
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:

      - "8000:8000"
volumes:
  database:
