# Generated by Django 3.1.6 on 2021-03-07 10:46

import core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_code',
            field=models.CharField(choices=[(core.choices.LanguageChoices['EN'], 'en'), (core.choices.LanguageChoices['DE'], 'de')], default='en', max_length=3),
        ),
    ]
